require 'rspec/core/rake_task'
require 'bundler'

Bundler.require

Dir.glob("lib/*.rb").each do |file|
  require_relative file
end

desc 'Load all'
task :default do
  Loader.new.run
end

desc 'Run all tests'
RSpec::Core::RakeTask.new(:test) do |t|
  t.fail_on_error = false
end